### ISSUE TITLE
Nucleus extraction

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#145]
Automated nucleus extraction:
- [x] Reseal cell with negative pressure
- [x] Monitor resistance to determine when to slow down / backup (#159)
- [x] Monitor resistance to determine when seal is complete or to give up
- [x] Nuzzle nucleus to get better access (?)
- [ ] PatchPipette flag to indicate that nucleus is ready to be collected
